Repository vigneshshettyin/Bulk-Mailer, pull requests merged in 2021-03, with the labels that each got.

#14 README.md corrected
  README.md
Labels: GSSOC21, LEVEL0

#16 Added a PR template
  .github/pull_request_template.md
Labels: GSSOC21, LEVEL0

#17 Create label.yml
  .github/workflows/label.yml
Labels: GSSOC21, LEVEL0

#21 add contributing.md
  contributing.md
Labels: GSSOC21, LEVEL0

#26 Added local password and email validation
  static/js/register.js
  templates/register.html
Labels: GSSOC21, Level3

#28 Added Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: GSSOC21, LEVEL0

#32 Added Tech Stack
  README.md
Labels: GSSOC21, LEVEL0

#33 Forgot password link fixed
  app.py
Labels: GSSOC21, Level1

#39 Added welcome bot
  .github/config.yml
Labels: GSSOC21, LEVEL0

#40 added the landing page mockup
  landing page/landing page/content.js
  landing page/landing page/index.html
  landing page/landing page/logo.png
  landing page/landing page/style.css
Labels: GSSOC21, Level3

#43 Updated "How to Use" in README file
  README.md
Labels: GSSOC21, LEVEL0, enhancement

#44 Added checkbox to issue templates
  .github/pull_request_template.md
Labels: GSSOC21, LEVEL0

#46 Add Google Login, Gravatar Image
  .gitignore
  app.py
  import.json
  templates/base.html
  templates/login.html
Labels: GSSOC21, Level3, enhancement

#55 Add Validations on Register and Login Page
  app.py
  static/js/login.js
  static/js/register.js
  templates/base.html
  templates/login.html
  templates/register.html
Labels: GSSOC21, Level3, enhancement

#58 Add Template Selection using Ajax
  app.py
  templates/mail.html
Labels: GSSOC21, Level3, enhancement

#60 Add landing page
  app.py
  import.json
  static/css/home.css
  static/img/gssoc.png
  templates/home.html
Labels: GSSOC21, Level3, enhancement
