Repository vigneshshettyin/Bulk-Mailer, pull requests merged in 2021-04, with the labels that each got.

#73 landing page redesigned
  landing page/landing page/css/styles.css
  landing page/landing page/images/favicon.png
  landing page/landing page/images/logo.png
  landing page/landing page/index.html
  landing page/landing page/try.py
Labels: GSSOC21, Level3, enhancement

#76 responsive design
  landing page/landing page/css/styles.css
  landing page/landing page/images/bootstrap.png
  landing page/landing page/images/css-3.png
  landing page/landing page/images/flask.png
  landing page/landing page/images/heroku.png
  landing page/landing page/images/html.png
  landing page/landing page/images/javascript.png
  landing page/landing page/images/jquery.png
  landing page/landing page/images/postgresql.png
  landing page/landing page/images/python.png
  landing page/landing page/images/sql.png
  landing page/landing page/index.html
Labels: GSSOC21, Level3, enhancement

#78 Update README.md
  README.md
Labels: GSSOC21, Level0, documentation

#83 [Gssoc'21] smooth Scrolling added
  static/css/style.css
  templates/landing.html
Labels: GSSOC21, Level2, enhancement

#88 [Gssoc'21] Added the back to top button
  templates/landing.html
Labels: GSSOC21, Level2, enhancement

#91 [Gssoc'21 ]Enhancing the social media icons in footer
  templates/landing.html
Labels: GSSOC21, Level2, enhancement

#92 [Gssoc'21] Fixed the bug in login and landing page
  templates/landing.html
  templates/login.html
Labels: GSSOC21, Level1

#95 Update README.md
  README.md
Labels: GSSOC21, Level1, documentation

#96 Added signup in navbar and oauthlib in requirements.txt
  requirements.txt
  templates/landing.html
Labels: GSSOC21, Level1

#97 [Gssoc'21] Added the preloader
  templates/landing.html
Labels: GSSOC21, Level3, enhancement

#99 Made remember me to be not a required field in login form.
  templates/login.html
Labels: GSSOC21, Level0

#102 [Gssoc'21] Added user name and avatar in navbar when user is logged in
  templates/landing.html
Labels: GSSOC21, Level2, bug

#103 Improved the responsive ness in mobile view
  static/css/landing.css
  templates/landing.html
Labels: GSSOC21, Level3, bug

#104 [Gssoc'21] Added the show password feature
  static/js/login.js
  static/js/register.js
  templates/login.html
  templates/register.html
Labels: GSSOC21, Level2, enhancement

#107 README enhancement
  README.md
Labels: GSSOC21, Level0, documentation

#108 [Gssoc'21] Added the dark mode
  static/js/darkmode.js
  templates/landing.html
  templates/login.html
  templates/register.html
Labels: GSSOC21, Level3, enhancement

#113 replaced confirmation to sweet alert
  templates/base.html
  templates/landing.html
Labels: GSSOC21, Level2, enhancement

#115 Added feature for navigating to dashboard from landing page
  templates/landing.html
Labels: GSSOC21, Level1, enhancement

#117 Contact section is added
  app.py
  static/css/landing.css
  templates/contact.html
  templates/landing.html
Labels: GSSOC21, Level3, enhancement

#120 Contact table in Dashboard
  app.py
  templates/base.html
  templates/contact_table.html
  templates/index.html
  templates/landing.html
Labels: GSSOC21, Level3, enhancement

#124 Added Download contact as CSV
  app.py
  templates/contact_table.html
Labels: GSSOC21, Level3, enhancement

#126 Added the Wave above footer
  templates/landing.html
Labels: GSSOC21, Level2, enhancement

#131 chore : Code lint & format (#130)
  .flake8
  .github/workflows/qa-checks.yml
  README.md
  app.py
  bulkmailer_qa_checks
  create.py
  email_utils/email_helper.py
  email_utils/email_verification.py
  requirements.txt
  validation.py
Labels: GSSOC21, Level3, enhancement

#135 added profile page template
  profile-page/index.html
  profile-page/user.css
Labels: GSSOC21, Level2

#138 Added Dark mode in Dashboard
  templates/base.html
  templates/group_list.html
  templates/landing.html
  templates/user_list.html
Labels: GSSOC21, Level3, enhancement
