Repository vigneshshettyin/Bulk-Mailer, pull requests merged in 2021-05, with the labels that each got.

#142 Replaced import.json with .env
  .env.sample
  README.md
  app.py
  import.json
Labels: GSSOC21, Level3, enhancement

#144 Added Simple Notify
  app.py
  email_utils/email_helper.py
  email_utils/email_verification.py
  static/css/simple-notify.min.css
  static/js/simple-notify.min.js
  templates/base.html
  templates/contact_table.html
  templates/error.html
  templates/forgot-password.html
  templates/group_list.html
  templates/group_members.html
  templates/index.html
  templates/landing.html
  templates/login.html
  templates/mail.html
  templates/register.html
  templates/templates.html
  templates/user_list.html
Labels: GSSOC21, Level3, enhancement

#146 Admin Middleware
  app.py
  templates/base.html
  templates/block.html
Labels: GSSOC21, Level3, enhancement

#150 Fix Use Template Button
  app.py
  templates/mail.html
Labels: GSSOC21, Level3, enhancement

#151 Add Forgot Password
  app.py
  email_utils/email_helper.py
  email_utils/email_verification.py
  static/js/forgot-pwd.js
  templates/emails/forgot-pwd.html
  templates/emails/register.html
  templates/forgot-password.html
Labels: GSSOC21, Level3, enhancement

#154 Decreasing the size on landing page
  static/css/landing.css
  templates/landing.html
Labels: GSSOC21, Level3, enhancement

#155 Detailer step by step video in read me
  README.md
Labels: GSSOC21, Level0, documentation, enhancement

#157 moved all css from landing.html to landing.css
  static/css/landing.css
  templates/landing.html
Labels: GSSOC21, Level1, enhancement

#160 Adding a Github Action for greeting
  .github/workflows/greetings.yml
Labels: GSSOC21, Level0, enhancement

#164 Fix Database URI
  app.py
Labels: GSSOC21, Level2, bug

#167 Add Flask-Migrate
  .env.sample
  README.md
  app.py
  config.py
  manage.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/65b9ede994d4_.py
  requirements.txt
Labels: GSSOC21, Level3, enhancement

#175 Add carousel to contributor section in landing page
  templates/landing.html
Labels: GSSOC21, Level3, enhancement

#196 improved the dark mode
  templates/base.html
Labels: GSSOC21, Level2, enhancement

#199 Banner text responsiveness fixed
  static/css/landing.css
  templates/landing.html
Labels: GSSOC21, Level2, enhancement

#201 set up lint
  README.md
  requirements.txt
Labels: GSSOC21, Level2, enhancement

#204 added darkmode for contact page
  templates/contact.html
  templates/login.html
Labels: GSSOC21, Level2, enhancement

#205 added transparent images
  static/img/gssoc.png
  static/img/login.png
  static/img/mail.png
Labels: GSSOC21, Level2

#207 Update README.md
  README.md
Labels: GSSOC21, Level0, documentation

#210 added-difference
  static/css/landing.css
  templates/landing.html
Labels: GSSOC21, Level3, enhancement

#213 made website responsive
  app.py
  config.py
  static/css/landing.css
  templates/landing.html
Labels: GSSOC21, Level3, enhancement

#220 added scrollbar
  static/css/landing.css
  static/css/style.css
  templates/404.html
  templates/base.html
  templates/contact.html
  templates/error.html
  templates/forgot-password.html
  templates/landing.html
  templates/login.html
  templates/register.html
  templates/thankyou.html
Labels: GSSOC21, Level3, enhancement

#222 customized landing.css
  static/css/landing.css
Labels: GSSOC21, Level3, enhancement
